# This is a basic workflow to help you get started with Actions

name: Github Actions Maven Build Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: mvn -B package --file WebAppHooks/catalogoProdotti/pom.xml
        
      - name: Step 4 - List the current directory
        run: ls -a

      - name: Step 4 - List the current directory
        run: |
          echo "deb http://archive.ubuntu.com/ubuntu precise main universe" sudo > /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y x11vnc xvfb firefox
          mkdir ~/.vnc
          x11vnc -storepasswd 1234 ~/.vnc/passwd
          bash -c 'echo "firefox" >> /.bashrc'
          


       # Runs a set of commands using the runners shell
      - name: Step 5 - Installare Node versione 10 in Ubuntu
        run: |
          sudo apt update
          sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
          curl -sL https://deb.nodesource.com/setup_10.x | sudo bash
          sudo apt install nodejs
          
          sudo npm cache clean -f
          sudo npm install -g n
          sudo n stable
          sudo n 10.18.0
          
          echo "Versione di node: "
          node -v
          echo "Versione di npm: "
          npm -v
          
          npm install
          echo "Provo ad INSTALLARE bcrypt"
          npm install bcrypt
          npm fund
          echo "vedi se ha fatto bene o no"
          
      - name: Step 6 - Unzip test-hooks ed installazione dentro test-guard di npm
        run: | 
          ls -a
          unzip test-hooks.zip
          cd test-hooks
          ls -a
          cd test-guard
          ls -a
          echo "Versione di node: "
          node -v
          echo "Versione di npm: "
          npm -v
          echo "Provo ad installare con npm install"
          npm install
          ls -a
          npm audit fix
          echo "Provo ad INSTALLARE bcrypt"
          npm install bcrypt
          npm fund
          echo "vedi se ha fatto bene o no"
    
      - name: Step 7 - Ottieni path file ftl da modificare con gli Hooks
        run: |
            cd WebAppHooks/catalogoProdotti/src/main/webapp/WEB-INF/view
            ls -a
            echo "Il path completo del file ftl da modificare Ã¨: "
            readlink -f indexOriginaleNoHook.ftl
            echo "Vediamo il contenuto del file ftl prima della modifica"
            cat indexOriginaleNoHook.ftl
              
        
      - name: Step 8 - Instrumenta l'applicazione iniettando gli Hooks
        run: |
            cd test-hooks
            cd test-guard
            ls -a
            echo "Visualizzazione file ftl prima dell injection! "
            cat /home/runner/work/repoWebAppHooks/repoWebAppHooks/WebAppHooks/catalogoProdotti/src/main/webapp/WEB-INF/view/indexOriginaleNoHook.ftl
            echo "Visualizza versione di node"
            node -v
            echo "... Cancellazione e successivo aggiornamento di node_modules ..."
            rm -rf node_modules/
            npm update
            echo "INJECTION adesso..."
            echo "Visualizza versione di node"
            node -v
            node main.js inject-hooks /home/runner/work/repoWebAppHooks/repoWebAppHooks/WebAppHooks/catalogoProdotti/src/main/webapp/WEB-INF/view/indexOriginaleNoHook.ftl --grammar freemarker
            echo "Visualizzazione file ftl dopo l'injection!!! "
            cat /home/runner/work/repoWebAppHooks/repoWebAppHooks/WebAppHooks/catalogoProdotti/src/main/webapp/WEB-INF/view/indexOriginaleNoHook.ftl
          
      - name: Step 9 - Install Geckodriver for Ubuntu
        run: |
            cd geckodriver-ubuntu
            wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
            tar -xvzf geckodriver*
            chmod +x geckodriver
            export PATH=$PATH:/home/runner/work/repoWebAppHooks/repoWebAppHooks/geckodriver-ubuntu/.
          
          
      - name: Step 10 - Set a DISPLAY
        run: |
            echo "Vediamo PRIMA se ha impostato Display"
            echo $DISPLAY
            export DISPLAY=:0
            echo "Vediamo DOPO se ha impostato Display"
            echo $DISPLAY
          
          
      - name: Step 11 - Run all the unit test classes
        run: |
            nmcli dev status
            cd WebAppHooks
            cd catalogoProdotti
            echo "Vediamo PRIMA se ha impostato Display"
            echo $DISPLAY
            export DISPLAY=172.17.0.1:0.0
            echo "Vediamo DOPO se ha impostato Display"
            echo $DISPLAY
            mvn -Dtest=Prova1 test
        
          
          
          
          
